export const ProposalStatus = Object.freeze({
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  CLOSED: 'CLOSED',
});

export const ApplicationStatus = Object.freeze({
  PENDING: 'PENDING',
  MEETING_REQUESTED: 'MEETING_REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

export const ProjectStatus = Object.freeze({
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  TERMINATED: 'TERMINATED',
});

export const MilestoneStatus = Object.freeze({
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  SUPERVISOR_GRADED: 'SUPERVISOR_GRADED',
  COORDINATOR_APPROVED: 'COORDINATOR_APPROVED',
  EXAMINER_ASSIGNED: 'EXAMINER_ASSIGNED',
  EXAMINER_GRADED: 'EXAMINER_GRADED',
  COMPLETED: 'COMPLETED',
});

export const GradeFieldType = Object.freeze({
  NUMBER: 'NUMBER',
  RUBRIC: 'RUBRIC',
  BOOLEAN: 'BOOLEAN',
  TEXT: 'TEXT',
});

export const DocumentType = Object.freeze({
  CV: 'CV',
  TRANSCRIPT: 'TRANSCRIPT',
  RESEARCH_PROPOSAL: 'RESEARCH_PROPOSAL',
  PROGRESS_REPORT: 'PROGRESS_REPORT',
  FINAL_REPORT: 'FINAL_REPORT',
  OTHER: 'OTHER',
});

export const NotificationType = Object.freeze({
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  MEETING_REQUESTED: 'MEETING_REQUESTED',
  PROJECT_STARTED: 'PROJECT_STARTED',
  MILESTONE_SUBMITTED: 'MILESTONE_SUBMITTED',
  MILESTONE_GRADED: 'MILESTONE_GRADED',
  MILESTONE_APPROVED: 'MILESTONE_APPROVED',
  EXAMINER_ASSIGNED: 'EXAMINER_ASSIGNED',
  DEFENSE_SCHEDULED: 'DEFENSE_SCHEDULED',
  GRADE_FINALIZED: 'GRADE_FINALIZED',
  GENERAL: 'GENERAL',
});
